version: 2
jobs:
  build:
    docker:
      - image: circleci/node: 8.11.3
    step:
      - checkout
      - run:
          name: Install Dependence
          command: |
            npm install
      - run: echo "Done"